[package]
name = "cargo-lock-prefetch"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo-lock = "10.1.0"
temp-dir = "0.1.16"
thiserror = "2.0.12"
anyhow = "1.0.98"
itertools = "0.14.0"
log = { version = "0.4.27", features = ["kv", "kv_serde"] }
