name: Publish Binaries
on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  upload-assets:
    env:
      BIN_NAME: cargo-lock-fetch
    name: upload-assets (${{ matrix.os }} ${{ matrix.target }})
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          locked: true
          bin: ${{ env.BIN_NAME }}
          archive: ${{ env.BIN_NAME }}-${{ github.event.release.tag_name }}-${{ matrix.target }}
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
