name: Publish Release

on:
  release:
    types: [ published ]

permissions:
  checks: write

jobs:
  ci:
    uses: ./.github/workflows/check-and-lint.yaml
    with:
      skip-examples: true
  publish:
    name: "Publish to crates.io"
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATES_IO_TOKEN }}
          args: --locked
