name: Build and Push mult-arch Docker
on:
  release:
    types:
      - published

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      BIN_NAME: cargo-lock-fetch

    name: "Build and Push to dockerhub"
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: echo "DOCKER_TAG=${GITHUB_EVENT_RELEASE_TAG_NAME#v}" >> $GITHUB_ENV
        env:
          GITHUB_EVENT_RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.BIN_NAME }}:${{ env.DOCKER_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.BIN_NAME }}:latest
          platforms: linux/amd64,linux/arm64
